language: cpp

matrix:
  include:

  - name: Ubuntu Linux 18.04
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - cmake
          - libclang-dev

  - name: macOS, XCode 11.3
    os: osx
    osx_image: xcode11.3
    addons:
      homebrew:
        update: true
        packages:
          - ncurses
          - sqlite3
          - llvm
    env:
      - PATH=/usr/local/opt/llvm/bin:${PATH}

before_install:
  - if [ "$(uname -s)" = "Linux" ]; then sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'; fi
  - if [ "$(uname -s)" = "Linux" ]; then travis_retry sudo apt-get -qq update; fi

script:
  - uname -sr && mkdir build && cd build && cmake .. && cmake --build . && sudo env "PATH=$PATH" cmake --build . -- install
